### ISSUE TITLE
plot_dsens_demod.m has a bug

### ISSUE THREAD

**Issue by ShoujunYu** [max-bera/MPA_mechan_MATLAB#1]
(Line 27) Function "TDMS_getStruct" cannot be found in any file.

Please add "TDMS_getStruct" function into this  project.

Thank you : )

**Comment by max-bera** [comment]
Hi! Sorry, I forgot to add the link to the function in the readme.
You can find it here:
https://au.mathworks.com/matlabcentral/fileexchange/30023-tdms-reader

**Comment by ShoujunYu** [comment]
Thank you for updating
